version: '3'
services:

  client:
    build:
      context: ./client
      dockerfile: .
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
  
  server:
    build:
      context: ./server
      dockerfile: .
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1