version: '3'
services:

  client:
    build:
      context: ./client
      dockerfile: .
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
  
  server:
    build:
      context: ./server
      dockerfile: .
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
  
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017